### ISSUE TITLE
Chat UI is sluggish on mobile browsers

### ISSUE THREAD

**Issue by tiltec** [foodsharing-dev/foodsharing-light#56]
e.g. while typing a message in a chat (https://beta.light.foodsharing.de/#/chats/243231), it takes some time until each letter shows up.

Tested in Chrome for Android and Lightning (Webview-based)

**Comment by nicksellen** [comment]
Can you try it on https://vuejs.org/v2/guide/forms.html?

I tried to find a quasar example, but the examples on the docs page only show on desktop view http://quasar-framework.org/components/input-textbox.html.

I did find this quasar app with a running demo though https://quasar-admin.firebaseapp.com/#/form

**Comment by nicksellen** [comment]
Maybe we can just add `.lazy` - https://vuejs.org/v2/guide/forms.html#lazy

I'll try it...

**Comment by tiltec** [comment]
All the demos work nice and smooth: http://quasar-framework.org/quasar-play/android/index.html#/showcase/form/text-input/textbox

Also the quasar-admin app.

**Comment by nicksellen** [comment]
We don't do anything special for the input field, so I think it's not related to the input specifically.

The `.lazy` option is useful anyway, as we don't need it to update per-letter. Then, at some point if we still want some performance optimizations we could dig deeper...

**Comment by nicksellen** [comment]
Ah, possibly it's running the scrollToBottom logic each time you type... will check...

**Comment by nicksellen** [comment]
Yes, it does call it on each letter and it triggers a redraw: https://gist.github.com/paulirish/5d52fb081b3570c81e3a#scroll-stuff

I'll fix that.

**Comment by tiltec** [comment]
I tried out #58 but it didn't help.

Also scrolling in the chat message view is slow. Maybe only with too many messages?
I tried in a conversation with only one message and it was smooth (input and scroll).

**Comment by nicksellen** [comment]
For the many messages issue we can use v-once https://vuejs.org/v2/api/#v-once

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicksellen** [comment]
#61 should also help
