### ISSUE TITLE
Store details: Notes should break on multiple lines

### ISSUE THREAD

**Issue by NerdyProjects** [foodsharing-dev/foodsharing-light#6]
The store notes are normally quite a long text. The current item does not allow a line break (and will not auto break).

The data actually mostly does not contain line breaks, so the component should break long lines automatically.

**Comment by djahnie** [comment]
This is one of the most important pieces of info IMHO. Please fix! ^_^

**Comment by nicksellen** [comment]
Being worked on in https://github.com/foodsharing-dev/foodsharing-light/pull/51 :)
