### ISSUE TITLE
CSRF broken, can't login or logout

### ISSUE THREAD

**Issue by tiltec** [foodsharing-dev/foodsharing-light#66]
The first API call is fine (e.g. login), but logout doesn't work afterwards.

Server response is `CSRF Failed: Referer checking failed - no Referer.` The request header has `Referrer Policy:no-referrer`.

Not sure what the problem is...

**Comment by nicksellen** [comment]
Can you try clearing your cookies?

**Comment by nicksellen** [comment]
Fixed in https://github.com/foodsharing-dev/foodsharing-light/commit/76d57791c9d16aaba4278614525f1e5f7d6ec91f
